# Generated by Django 5.2.6 on 2025-09-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ridefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final fare after ride completion.', max_digits=10, null=True),
        ),
    ]
