# Generated by Django 5.2.6 on 2025-09-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('rides', '0003_ride_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when payment was confirmed.', null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card')], help_text='Method of payment (Cash, UPI, Card).', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='UNPAID', help_text='Tracks whether the ride is paid or unpaid.', max_length=8),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['payment_status'], name='rides_ride_payment_c94039_idx'),
        ),
    ]
