# Generated by Django 5.2.6 on 2025-09-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_ride_paid_at_ride_payment_method_ride_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when ride was completed.', null=True),
        ),
    ]
