# Generated by Django 5.2.6 on 2025-09-12 06:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(max_length=255)),
                ('dropoff_address', models.CharField(max_length=255)),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('drop_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('drop_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=16)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, help_text='Driver assigned to this ride (null until accepted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='accounts.driver')),
                ('rider', models.ForeignKey(help_text='Rider who requested the ride.', on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='accounts.rider')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status'], name='accounts_ri_status_b2d1f5_idx'), models.Index(fields=['requested_at'], name='accounts_ri_request_9afdbe_idx')],
            },
        ),
    ]
