# Generated by Django 5.2.6 on 2025-09-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='current_latitude',
            field=models.FloatField(blank=True, help_text='Latest reported latitude from driver device.', null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='current_longitude',
            field=models.FloatField(blank=True, help_text='Latest reported longitude from driver device.', null=True),
        ),
    ]
