# Generated by Django 5.2.4 on 2025-09-22 05:52

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_menucategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='operating_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], help_text='Days when the restaurant is open (e.g., Mon, Tue, Wed)', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.OneToOneField(blank=True, help_text='One-to-one mapping with Address', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.address'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(help_text='Name of the restaurant', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(help_text='Contact number', max_length=15),
        ),
    ]
