# Generated by Django 5.2.4 on 2025-10-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_restaurant_operating_days_alter_restaurant_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(unique=True)),
                ('capacity', models.PositiveIntegerField(help_text='Number of people the table can seat')),
                ('is_available', models.BooleanField(default=True, help_text='Whether the table is currently available')),
            ],
        ),
    ]
