# Generated by Django 5.2.4 on 2025-10-11 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_table'),
        ('products', '0009_menuitem_is_daily_special'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating given by the user (1–5)')),
                ('comment', models.TextField(blank=True, help_text='Optional text feedback provided by the user')),
                ('review_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the review was submitted')),
                ('menu_item', models.ForeignKey(help_text='The menu item being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.menuitem')),
                ('user', models.ForeignKey(help_text='The user who submitted this review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Review',
                'verbose_name_plural': 'User Reviews',
                'ordering': ['-review_date'],
                'indexes': [models.Index(fields=['menu_item'], name='home_userre_menu_it_645a7a_idx'), models.Index(fields=['user'], name='home_userre_user_id_51b06a_idx')],
                'unique_together': {('user', 'menu_item')},
            },
        ),
    ]
