# Generated by Django 5.2.4 on 2025-09-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='contact',
        ),
    ]
