# Generated by Django 5.2.4 on 2025-09-16 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default='PENDING', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderstatus'),
        ),
    ]
