# Generated by Django 5.2.4 on 2025-10-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_created_at_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_order_id',
            field=models.CharField(editable=False, help_text='Unique alphanumeric ID for the order', max_length=12, null=True, unique=True),
        ),
    ]
