# Generated by Django 5.2.4 on 2025-10-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_daily_special',
            field=models.BooleanField(default=False, help_text='Mark this item as a daily special'),
        ),
    ]
