# Generated by Django 5.2.4 on 2025-10-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_menuitem_is_daily_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Indicates whether the menu item is currently available'),
        ),
    ]
