# Generated by Django 5.2.4 on 2025-10-16 04:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_menuitem_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage for this item (e.g., 10 for 10%)', max_digits=5),
        ),
    ]
